# ADDITION

In [1]:
import numpy as np

A = np.array([[1,5,6],[8,-2,4],[-7,3,9]])
B = np.array([[6,-5,-2],[5,7,-4],[-9,6,8]])
C = A+B
print(C)

[[  7   0   4]
 [ 13   5   0]
 [-16   9  17]]


# SUBTRACTION

In [2]:
import numpy as np

A = np.array([[1,5,6],[8,-2,4],[-7,3,9]])
B = np.array([[6,-5,-2],[5,7,-4],[-9,6,8]])
C = A-B
print(C)

[[-5 10  8]
 [ 3 -9  8]
 [ 2 -3  1]]


# MULTIPLICATION

In [4]:
import numpy as np
 
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])
res = np.dot(mat1,mat2)
print(res)

[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]
