In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [4]:
#McCulloh Pitt model for AND model
import numpy as np

def McAnd(x,w,t):
    net = np.dot(x,w)
    if net>t:
        output = 1
    else:
        output = 0
    return output

x0 = np.array([0,0,1])
x1 = np.array([0,1,1])
x2 = np.array([1,0,1])
x3 = np.array([1,1,1])
w = np.array([1,1,-1])

t = 0
ans1 = McAnd(x0,w,t)
print (x0, "value", ans1)
ans2 = McAnd(x1,w,t)
print (x1, "value", ans2)
ans3 = McAnd(x2,w,t)
print (x2, "value", ans3)
ans4 = McAnd(x3,w,t)
print (x3, "value", ans4)

[0 0 1] value 0
[0 1 1] value 0
[1 0 1] value 0
[1 1 1] value 1


In [5]:
#McCulloh Pitt model for OR model
import numpy as np

def McOr(x,w,t):
    net = np.dot(x,w)
    if net>t:
        output = 1
    else:
        output = 0
    return output
x0 = np.array([0,0,1])
x1 = np.array([0,1,1])
x2 = np.array([1,0,1])
x3 = np.array([1,1,1])
w = np.array([8,7,-3])
t = 0
ans1 = McOr(x0,w,t)
print (x0, "value", ans1)
ans2 = McOr(x1,w,t)
print (x1, "value", ans2)
ans3 = McOr(x2,w,t)
print (x2, "value", ans3)
ans4 = McOr(x3,w,t)
print (x3, "value", ans4)

[0 0 1] value 0
[0 1 1] value 1
[1 0 1] value 1
[1 1 1] value 1


In [6]:
#McCulloh Pitt model for NOT model
import numpy as np

def McNOT(x,w,t):
    net = np.dot(x,w)
    if net>t:
        output = 1
    else:
        output = 0
    return output
x0 = np.array([1,0])
x1 = np.array([1,1])
w = np.array([1,-1])
t = 0
ans1 = McNOT(x0,w,t)
print (x0, "value", ans1)
ans2 = McNOT(x1,w,t)
print (x1, "value", ans2)

[1 0] value 1
[1 1] value 0


In [9]:
#Matrix Addition

import numpy as np

A = np.array([[1,5,6],[8,-2,4],[-7,3,9]])
B = np.array([[6,-5,-2],[5,7,-4],[-9,6,8]])
C = A+B
print(C)

[[  7   0   4]
 [ 13   5   0]
 [-16   9  17]]


In [10]:
#Matrix Subtraction

import numpy as np

A = np.array([[1,5,6],[8,-2,4],[-7,3,9]])
B = np.array([[6,-5,-2],[5,7,-4],[-9,6,8]])
C = A-B
print(C)

[[-5 10  8]
 [ 3 -9  8]
 [ 2 -3  1]]


In [11]:
#Matrix Multiplication

import numpy as np

A = np.array([[1,5,6],[8,-2,4],[-7,3,9]])
B = np.array([[6,-5,-2],[5,7,-4],[-9,6,8]])
C = A*B
print(C)

[[  6 -25 -12]
 [ 40 -14 -16]
 [ 63  18  72]]
