In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
x = np.array([2,5,7])
print(x)
print("Dimension ", x.ndim)
print("Shape ", x.shape)

y = np.array([[2,5,7],[3,6,8]])
print(y)
print("Dimension ", y.ndim)
print("Shape ", y.shape)

z = np.array([[[1,3,5,6],[2,4,6,7],[1,2,3,4]],[[4,3,2,1],[7,9,11,12],[8,10,12,9]]])
print(z)
print("Dimension ", z.ndim)
print("Shape ", z.shape)

[2 5 7]
Dimension  1
Shape  (3,)
[[2 5 7]
 [3 6 8]]
Dimension  2
Shape  (2, 3)
[[[ 1  3  5  6]
  [ 2  4  6  7]
  [ 1  2  3  4]]

 [[ 4  3  2  1]
  [ 7  9 11 12]
  [ 8 10 12  9]]]
Dimension  3
Shape  (2, 3, 4)


In [6]:
#Simple operation to illustrate constant and variable

import tensorflow as tf
x = tf.constant(2)
y = tf.Variable(x+4)
total=x+y
print(total)

tf.Tensor(8, shape=(), dtype=int32)


# ADDITION

In [14]:

import tensorflow as tf
import numpy as np

matrix_1 = np.array([(1,2,3),(3,2,1),(1,1,1)],dtype = 'int32')
matrix_2 = np.array([(0,0,0),(-1,0,1),(3,3,4)],dtype = 'int32')
print("The first matrix is ")
print (matrix_1)
print("The second matrix is ")
print (matrix_2)
print("The sum is ")
matrix_1 = tf.constant(matrix_1)
matrix_2 = tf.constant(matrix_2)
matrix_sum = tf.add(matrix_1, matrix_2)
print((matrix_sum))

The first matrix is 
[[1 2 3]
 [3 2 1]
 [1 1 1]]
The second matrix is 
[[ 0  0  0]
 [-1  0  1]
 [ 3  3  4]]
The sum is 
tf.Tensor(
[[1 2 3]
 [2 2 2]
 [4 4 5]], shape=(3, 3), dtype=int32)


# SUBTRACTION

In [15]:

import tensorflow as tf
import numpy as np

matrix_1 = np.array([(1,2,3),(3,2,1),(1,1,1)],dtype = 'int32')
matrix_2 = np.array([(0,0,0),(-1,0,1),(3,3,4)],dtype = 'int32')
print("The first matrix is ")
print (matrix_1)
print("The second matrix is ")
print (matrix_2)
print("The Difference is ")
matrix_1 = tf.constant(matrix_1)
matrix_2 = tf.constant(matrix_2)
matrix_diff = tf.subtract(matrix_1, matrix_2)
print((matrix_diff))

The first matrix is 
[[1 2 3]
 [3 2 1]
 [1 1 1]]
The second matrix is 
[[ 0  0  0]
 [-1  0  1]
 [ 3  3  4]]
The Difference is 
tf.Tensor(
[[ 1  2  3]
 [ 4  2  0]
 [-2 -2 -3]], shape=(3, 3), dtype=int32)


# MULTIPLICATION

In [16]:
import tensorflow as tf
import numpy as np

matrix_1 = np.array([(1,2,3),(3,2,1),(1,1,1)],dtype = 'int32')
matrix_2 = np.array([(0,0,0),(-1,0,1),(3,3,4)],dtype = 'int32')
print("The first matrix is ")
print (matrix_1)
print("The second matrix is ")
print (matrix_2)
print("The product is ")
matrix_1 = tf.constant(matrix_1)
matrix_2 = tf.constant(matrix_2)
matrix_prod = tf.matmul(matrix_1, matrix_2)
print((matrix_prod))

The first matrix is 
[[1 2 3]
 [3 2 1]
 [1 1 1]]
The second matrix is 
[[ 0  0  0]
 [-1  0  1]
 [ 3  3  4]]
The product is 
tf.Tensor(
[[ 7  9 14]
 [ 1  3  6]
 [ 2  3  5]], shape=(3, 3), dtype=int32)
